### ISSUE TITLE
Optimization cutoff algorithm

### ISSUE THREAD

**Issue by KDGoodenough** [dbouman1/iccp-assignment-2#1]
To minimize the calculations for the energy, we can use a cutoff radius. There are a few ways I think we could tackle this:

1) Calculate for each possible new nodal point which other nodal points fall in the cutoff radius. If they fall in the cutoff radius, we calculate the energy contribution for that nodal point

2) We can calculate the cutoff radius from the last nodal point we actually created. Then for each of the possible new nodal points, we would have to recalculate the distance between the possible new nodal point and all the nodal points that fell in the cutoff radius. From this we can calculate the energy difference. We would have to take a larger cutoff radius in comparison with the first method.

I'm pretty sure the second method is the most efficient of the two, and I haven't been able to come up with something else. Maybe we could do something like the listtracking that was an option for the argon simulation, but I'm not sure how to implement that. Do you have any other ideas?

**Comment by danielbouman** [comment]
Lets go for list tracking.

**Comment by danielbouman** [comment]
A list tracking module is implemented. Some documentation is included. Detailed usage instructions will follow.
